### ISSUE TITLE
Enhance TextBlock

### ISSUE THREAD

**Issue by trailblazercombi** [domcouhrik/shapesge#2]
Give TextBlock the ability to calculate its width (the width of the text displayed).
Potentially also add autofit and text wrapping abilities.

**Comment by domcouhrik** [comment]
Split into tasks:

- [x] Proper text alignment from top left corner
- [x] Getter for width and height
- [x] Adjustable spacing between lines
- [x] Automatic text wrapping
- [ ] Autofit to size constraints

**Comment by domcouhrik** [comment]
### _**For task 1 (Proper text alignment from top left corner)**_
Unlike other shapes, this one is not rendered directly in `TextDrawable` -- instead, it utilizes `Graphics2D.drawString()`.
The `drawString()` method can only draw a single line at a time, so a `for` loop is used to draw each line separately.
To determine the height of each line (aka offset to the next line), `FontMetrics.getHeight()` is used.

Fonts are rendered with the reference point being at the character's start point on the line:
> ![FontMetrics-1](https://github.com/user-attachments/assets/9a23ace0-0550-496b-813b-cb76f94425c8)

The character then has **ascent** (size above the baseline), **descent** (size below the baseline) and **advance** (width) values.
Adding the ascent and descent together yields in the **character's total height**, which is precisely what `FontMetrics.getHeight()` does*.

In ShapesGE `TextDrawable.draw()` first sets the `Graphics2D` context with the colour and font, and only then renders the String.
However, it leaves behind no traces (the `Graphics2D` context is lost after the method is finished) and `draw()` is called only from `GameObjects.drawAll()` -- hardly a suitable place for a getter.

The proposal is instead as follows:
Whenever `draw()` is called, an attribute is stored in `TextDrawable` that keeps the `FontMetrics` used last.
This should allow the creation of getters for width and height of the `TextBlock`.

*`FontMetrics.getHeight()` also adds an extra `0`, which is the **leading space** (built-in whitespace between two lines). This is, presumably, meant to be overridden by subclasses inheriting`FontMetrics`.

**Comment by domcouhrik** [comment]
### _**For task 2 (Getters for width and height)**_
```java
@Override
    public void draw(Graphics2D canvas) {
        canvas.setColor(this.getColor());

        canvas.setFont(this.font);
        this.lastUsedMetrics = canvas.getFontMetrics();
        var y = this.getYPosition() + this.lastUsedMetrics.getAscent();
        final var lineHeight = this.lastUsedMetrics.getHeight();

        for (String line : this.text) {
            canvas.drawString(line, this.getXPosition(), y);
            y += lineHeight + this.lineSpacing;
        }
    }
```
The getters don't seem to work, due to `NullPointerException` of `FontMetrics lastUsedMetrics`.
This is happening because this implementation relies on `draw()` having been called at least once before the getters function.

**Comment by domcouhrik** [comment]
### **_For task 2 (Getters for width and height)_**
I asked ChatGPT for help. It came up with the idea of using a mock BufferedImage to get the Graphics object required to extract FontMetrics to calculate the width and height.
```java
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

public class TextBlockDimensions {

    public static void main(String[] args) {
        // Example usage
        Font font = new Font("Arial", Font.PLAIN, 12);
        String[] lines = {"Hello, world!", "This is a test.", "Java programming."};
        int lineSpacing = 5;

        int[] dimensions = getTextBlockDimensions(font, lines, lineSpacing);
        System.out.println("Width: " + dimensions[0]);
        System.out.println("Height: " + dimensions[1]);
    }

    public static int[] getTextBlockDimensions(Font font, String[] lines, int lineSpacing) {
        // Create a temporary BufferedImage to get the FontMetrics
        BufferedImage img = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        Graphics g = img.getGraphics();
        FontMetrics metrics = g.getFontMetrics(font);

        int width = 0;
        int height = 0;

        for (String line : lines) {
            int lineWidth = metrics.stringWidth(line);
            width = Math.max(width, lineWidth);
            height += metrics.getHeight();
        }

        // Add the line spacing to the height
        if (lines.length > 1) {
            height += (lines.length - 1) * lineSpacing;
        }

        // Clean up graphics context
        g.dispose();

        return new int[]{width, height};
    }
```

**Comment by domcouhrik** [comment]
### _**For task 4 (Automatic text wrapping)**_
```java
if (this.maxWidth <= 0) {
            // If the maximum width is not set, TextDrawable works as normal.
            for (String line : this.text) {
                // Draw the line.
                canvas.drawString(line, this.getXPosition(), y);
                y += lineHeight + this.lineSpacing;
            }
        } else {
            // If the maximum width is set, TextDrawable splits all lines into shorter ones.
            for (String line : this.text) {
                String[] words = line.split(" ");
                // Create a new line builder.
                var newLine = new StringBuilder();
                var lenLine = 0;
                // Parse all words. If the entire line fits, it SHOULD yield the same result as if the limit did not exist.
                for (String word : words) {
                    int newLenLine = lenLine + metrics.stringWidth(word);
                    if (newLenLine > this.maxWidth) {
                        // Once the limit is reached...
                        // Check if the word we're processing will fit into a line on its own.
                        if (metrics.stringWidth(word) > this.maxWidth) {
                            // If it doesn't, split it further.
                            char[] chars = word.toCharArray();
                            // And assemble characters up to the limit.
                            var wordMaker = new StringBuilder();
                            int lenWord = metrics.charWidth('-');
                            for (char aChar : chars) {
                                if (lenWord + metrics.charWidth(aChar) > this.maxWidth) {
                                    // If the limit is reached, hyphenate the word, draw it and reset the builder.
                                    wordMaker.append('-');
                                    canvas.drawString(wordMaker.toString(), this.getXPosition(), y);
                                    y += lineHeight + this.lineSpacing;
                                    wordMaker = new StringBuilder();
                                    lenWord = metrics.charWidth('-');
                                } else {
                                    wordMaker.append(aChar);
                                    lenWord += metrics.charWidth(aChar);
                                }
                            }
                        } else {
                            // Draw the line and reset the line builder.
                            canvas.drawString(newLine.toString(), this.getXPosition(), y);
                            y += lineHeight + this.lineSpacing;
                            newLine = new StringBuilder();
                            lenLine = 0;
                        }
                    } else {
                        newLine.append(word).append(" ");
                        lenLine = newLenLine;
                    }
                }
                // Once we're done processing all words in the line, draw the leftovers.
                canvas.drawString(newLine.toString(), this.getXPosition(), y);
                y += lineHeight + this.lineSpacing;
            }
```
This code seems to work fine, except that it always skips the last token (word) at the end of the line.
It is also incredibly wordy and messy (not exactly maintainable).

**Comment by domcouhrik** [comment]
### _**For task 4 (automatic text wrapping)**_
This hideous code was replaced with better code (thanks to ChatGPT's ideas).

**Comment by domcouhrik** [comment]
### Final behaviour
The method `String[] TextDrawable.wrap(String[])`:
1. Checks if the text wrapping is enabled (if `maxWidth` is 0 or lower). If it isn't, returns the original text.
2. Tries to break the text into multiple lines based on `maxWidth` (set by `void enableTextWrapping(int)`).
3. If `findBreakPoint(String)` cannot find a suitable break point near the limit, `hyphenate(String)` is used instead.
4. `hyphenate(String)` does not take syllables into account, and breaks the line at the very limit (taking into account the length of the hyphen).
